package net.spotapps.tester.model;

import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonPropertyDescription;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;

@Entity
@Table(name = "user_profiles")
public class UserProfile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "The unique identifier, generated by UserProfileService on addition")
    @Column(name = "user_id")
    private Long userId;

    @Schema(description  = "List of references to images of the user")
    @OneToMany(mappedBy = "userProfile")
    private List<UserImage> images;

    @Schema(description = "The contact information and preferences of the user")
    @JsonPropertyDescription("The contact information and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "contact")
    private ContactPreference contact;

    @Schema(description = "The location and proximity preferences of the user")
    @JsonPropertyDescription("The location and proximity preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "location")
    private LocationPreference location;

    @Schema(description = "The socializing preference of the user")
    @JsonPropertyDescription("The socializing preference of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "social")
    private SocialPreference social;

    @Schema(description = "The gender identity and preferences of the user")
    @JsonPropertyDescription("The gender identity and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "gender")
    private GenderPreference gender;

    @Schema(description = "The relationship status and style preferences of the user")
    @JsonPropertyDescription("The relationship status and style preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "relationship")
    private RelationshipPreference relationship;

    @Schema(description = "The child having status and preferences of the user")
    @JsonPropertyDescription("The child having status and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "children")
    private ChildrenPreference children;

    @Schema(description = "The age and ranged preferences of the user")
    @JsonPropertyDescription("The age and ranged preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "age")
    private AgePreference age;

    @Schema(description = "The religious practice and preferences of the user")
    @JsonPropertyDescription("The religious practice and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "religion")
    private ReligionPreference religion;

    @Schema(description = "The education status and preferences of the user")
    @JsonPropertyDescription("The education status and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "education")
    private EducationPreference education;

    @Schema(description = "The language speaking status and preferences of the user")
    @JsonPropertyDescription("The language speaking status and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "language")
    private LanguagePreference language;

    @Schema(description = "The extracurricular partakings and preferences of the user")
    @JsonPropertyDescription("The extracurricular partakings and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "vice")
    private VicePreference vice;

    @Schema(description = "The pet having status and preferences of the user")
    @JsonPropertyDescription("The pet having status and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "pets")
    private PetsPreference pets;

    @Schema(description = "The preferences of the user regarding the dynamics centered around travel")
    @JsonPropertyDescription("The preferences of the user regarding the dynamics centered around travel")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "travel")
    private TravelPreference travel;

    @Schema(description = "The dietary restrictions and preferences of the user")
    @JsonPropertyDescription("The dietary restrictions and preferences of the user")
    @OneToOne(mappedBy = "userProfile", cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn(name = "diet")
    private DietPreference diet;

    @Schema(description = "The things and activities the user is interested in")
    @OneToMany(mappedBy = "userProfile")
    private List<UserInterest> interests;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public List<UserImage> getImages() {
        return images;
    }

    public void setImages(List<UserImage> images) {
        this.images = images;
    }

    public ContactPreference getContact() {
        return contact;
    }

    public void setContact(ContactPreference contact) {
        this.contact = contact;
    }

    public LocationPreference getLocation() {
        return location;
    }

    public void setLocation(LocationPreference location) {
        this.location = location;
    }

    public SocialPreference getSocial() {
        return social;
    }

    public void setSocial(SocialPreference social) {
        this.social = social;
    }

    public GenderPreference getGender() {
        return gender;
    }

    public void setGender(GenderPreference gender) {
        this.gender = gender;
    }

    public RelationshipPreference getRelationship() {
        return relationship;
    }

    public void setRelationship(RelationshipPreference relationship) {
        this.relationship = relationship;
    }

    public ChildrenPreference getChildren() {
        return children;
    }

    public void setChildren(ChildrenPreference children) {
        this.children = children;
    }

    public AgePreference getAge() {
        return age;
    }

    public void setAge(AgePreference age) {
        this.age = age;
    }

    public ReligionPreference getReligion() {
        return religion;
    }

    public void setReligion(ReligionPreference religion) {
        this.religion = religion;
    }

    public EducationPreference getEducation() {
        return education;
    }

    public void setEducation(EducationPreference education) {
        this.education = education;
    }

    public LanguagePreference getLanguage() {
        return language;
    }

    public void setLanguage(LanguagePreference language) {
        this.language = language;
    }

    public VicePreference getVice() {
        return vice;
    }

    public void setVice(VicePreference vice) {
        this.vice = vice;
    }

    public PetsPreference getPets() {
        return pets;
    }

    public void setPets(PetsPreference pets) {
        this.pets = pets;
    }

    public TravelPreference getTravel() {
        return travel;
    }

    public void setTravel(TravelPreference travel) {
        this.travel = travel;
    }

    public DietPreference getDiet() {
        return diet;
    }

    public void setDiet(DietPreference diet) {
        this.diet = diet;
    }

    public List<UserInterest> getInterests() {
        return interests;
    }

    public void setInterests(List<UserInterest> interests) {
        this.interests = interests;
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null || getClass() != obj.getClass())
            return false;
        UserProfile other = (UserProfile) obj;
        return Objects.equals(userId, other.userId);
    }

    @Override
    public String toString() {
        return "UserProfile [userId=" + userId + "]";
    }

    

}
