package net.spotapps.tester.dto;

import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import jakarta.validation.Valid;
import net.spotapps.tester.model.UserProfile;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "userId",
        "images",
        "contactPreference",
        "locationPreference",
        "socialPreference",
        "genderPreference",
        "relationshipPreference",
        "childrenPreference",
        "agePreference",
        "religionPreference",
        "educationPreference",
        "languagePreference",
        "vicePreference",
        "petsPreference",
        "travelPreference",
        "dietPreference",
        "interests"
})
public class UserProfileDto {

    @JsonProperty(required = true)
    @JsonPropertyDescription("The unique identifier, generated by UserProfileService on addition")
    private Long userId;

    @JsonProperty(required = true)
    @JsonPropertyDescription("List of references to images of the user")
    private List<UserImageDto> images;

    @JsonProperty(required = true)
    @JsonPropertyDescription("The things and activities the user is interested in")
    private List<UserInterestDto> interests;

    @JsonProperty(value = "contactPreference", required = true)
    @JsonPropertyDescription("The user's contact preferences")
    @Valid
    private ContactPreferenceDto contactPreference;

    @JsonProperty(value = "locationPreference", required = true)
    @JsonPropertyDescription("The user's location preferences")
    @Valid
    private LocationPreferenceDto locationPreference;

    @JsonProperty(value = "socialPreference", required = true)
    @JsonPropertyDescription("The user's social preferences")
    @Valid
    private SocialPreferenceDto socialPreference;

    @JsonProperty(value = "genderPreference", required = true)
    @JsonPropertyDescription("The user's gender preferences")
    @Valid
    private GenderPreferenceDto genderPreference;

    @JsonProperty(value = "relationshipPreference", required = true)
    @JsonPropertyDescription("The user's relationship preferences")
    @Valid
    private RelationshipPreferenceDto relationshipPreference;

    @JsonProperty(value = "childrenPreference", required = true)
    @JsonPropertyDescription("The user's children preferences")
    @Valid
    private ChildrenPreferenceDto childrenPreference;

    @JsonProperty(value = "agePreference", required = true)
    @JsonPropertyDescription("The user's age preferences")
    @Valid
    private AgePreferenceDto agePreference;

    @JsonProperty(value = "religionPreference", required = true)
    @JsonPropertyDescription("The user's religion preferences")
    @Valid
    private ReligionPreferenceDto religionPreference;

    @JsonProperty(value = "educationPreference", required = true)
    @JsonPropertyDescription("The user's education preferences")
    @Valid
    private EducationPreferenceDto educationPreference;

    @JsonProperty(value = "languagePreference", required = true)
    @JsonPropertyDescription("The user's language preferences")
    @Valid
    private LanguagePreferenceDto languagePreference;

    @JsonProperty(value = "vicePreference", required = true)
    @JsonPropertyDescription("The user's vice preferences")
    @Valid
    private VicePreferenceDto vicePreference;

    @JsonProperty(value = "petsPreference", required = true)
    @JsonPropertyDescription("The user's pets preferences")
    @Valid
    private PetsPreferenceDto petsPreference;

    @JsonProperty(value = "travelPreference", required = true)
    @JsonPropertyDescription("The user's travel preferences")
    @Valid
    private TravelPreferenceDto travelPreference;

    @JsonProperty(value = "dietPreference", required = true)
    @JsonPropertyDescription("The user's diet preferences")
    @Valid
    private DietPreferenceDto dietPreference;

    public UserProfileDto() {
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public List<UserImageDto> getImages() {
        return images;
    }

    public void setImages(List<UserImageDto> images) {
        this.images = images;
    }

    public List<UserInterestDto> getInterests() {
        return interests;
    }

    public void setInterests(List<UserInterestDto> interests) {
        this.interests = interests;
    }

    public ContactPreferenceDto getContactPreference() {
        return contactPreference;
    }

    public void setContactPreference(ContactPreferenceDto contactPreference) {
        this.contactPreference = contactPreference;
    }

    public LocationPreferenceDto getLocationPreference() {
        return locationPreference;
    }

    public void setLocationPreference(LocationPreferenceDto locationPreference) {
        this.locationPreference = locationPreference;
    }

    public SocialPreferenceDto getSocialPreference() {
        return socialPreference;
    }

    public void setSocialPreference(SocialPreferenceDto socialPreference) {
        this.socialPreference = socialPreference;
    }

    public GenderPreferenceDto getGenderPreference() {
        return genderPreference;
    }

    public void setGenderPreference(GenderPreferenceDto genderPreference) {
        this.genderPreference = genderPreference;
    }

    public RelationshipPreferenceDto getRelationshipPreference() {
        return relationshipPreference;
    }

    public void setRelationshipPreference(RelationshipPreferenceDto relationshipPreference) {
        this.relationshipPreference = relationshipPreference;
    }

    public ChildrenPreferenceDto getChildrenPreference() {
        return childrenPreference;
    }

    public void setChildrenPreference(ChildrenPreferenceDto childrenPreference) {
        this.childrenPreference = childrenPreference;
    }

    public AgePreferenceDto getAgePreference() {
        return agePreference;
    }

    public void setAgePreference(AgePreferenceDto agePreference) {
        this.agePreference = agePreference;
    }

    public ReligionPreferenceDto getReligionPreference() {
        return religionPreference;
    }

    public void setReligionPreference(ReligionPreferenceDto religionPreference) {
        this.religionPreference = religionPreference;
    }

    public EducationPreferenceDto getEducationPreference() {
        return educationPreference;
    }

    public void setEducationPreference(EducationPreferenceDto educationPreference) {
        this.educationPreference = educationPreference;
    }

    public LanguagePreferenceDto getLanguagePreference() {
        return languagePreference;
    }

    public void setLanguagePreference(LanguagePreferenceDto languagePreference) {
        this.languagePreference = languagePreference;
    }

    public VicePreferenceDto getVicePreference() {
        return vicePreference;
    }

    public void setVicePreference(VicePreferenceDto vicePreference) {
        this.vicePreference = vicePreference;
    }

    public PetsPreferenceDto getPetsPreference() {
        return petsPreference;
    }

    public void setPetsPreference(PetsPreferenceDto petsPreference) {
        this.petsPreference = petsPreference;
    }

    public TravelPreferenceDto getTravelPreference() {
        return travelPreference;
    }

    public void setTravelPreference(TravelPreferenceDto travelPreference) {
        this.travelPreference = travelPreference;
    }

    public DietPreferenceDto getDietPreference() {
        return dietPreference;
    }

    public void setDietPreference(DietPreferenceDto dietPreference) {
        this.dietPreference = dietPreference;
    }

    @Override
    public int hashCode() {
        return Objects.hash(contactPreference, locationPreference, socialPreference, genderPreference,
                relationshipPreference, childrenPreference, agePreference, religionPreference, educationPreference,
                languagePreference, vicePreference, petsPreference, travelPreference, dietPreference, images, interests,
                userId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UserProfileDto other = (UserProfileDto) obj;
        return Objects.equals(contactPreference, other.contactPreference)
                && Objects.equals(locationPreference, other.locationPreference)
                && Objects.equals(socialPreference, other.socialPreference)
                && Objects.equals(genderPreference, other.genderPreference)
                && Objects.equals(relationshipPreference, other.relationshipPreference)
                && Objects.equals(childrenPreference, other.childrenPreference)
                && Objects.equals(agePreference, other.agePreference)
                && Objects.equals(religionPreference, other.religionPreference)
                && Objects.equals(educationPreference, other.educationPreference)
                && Objects.equals(languagePreference, other.languagePreference)
                && Objects.equals(vicePreference, other.vicePreference)
                && Objects.equals(petsPreference, other.petsPreference)
                && Objects.equals(travelPreference, other.travelPreference)
                && Objects.equals(dietPreference, other.dietPreference) && Objects.equals(images, other.images)
                && Objects.equals(interests, other.interests) && Objects.equals(userId, other.userId);
    }

    @Override
    public String toString() {
        return "UserProfileDto [userId=" + userId + ", images=" + images + ", interests=" + interests
                + ", contactPreference=" + contactPreference + ", locationPreference=" + locationPreference
                + ", socialPreference=" + socialPreference + ", genderPreference=" + genderPreference
                + ", relationshipPreference=" + relationshipPreference + ", childrenPreference=" + childrenPreference
                + ", agePreference=" + agePreference + ", religionPreference=" + religionPreference
                + ", educationPreference=" + educationPreference + ", languagePreference=" + languagePreference
                + ", vicePreference=" + vicePreference + ", petsPreference=" + petsPreference + ", travelPreference="
                + travelPreference + ", dietPreference=" + dietPreference + "]";
    }

    public static UserProfileDto convertUserProfileToDto(final UserProfile userProfile) {

        UserProfileDto dto = new UserProfileDto();
        dto.setUserId(userProfile.getUserId());

        if (userProfile.getImages() != null) {
            dto.setImages(userProfile.getImages().stream()
                    .map(image -> {
                        UserImageDto imageDto = new UserImageDto();
                        imageDto.setImageId(image.getImageId());
                        imageDto.setImage(image.getImage());
                        return imageDto;
                    })
                    .toList());
        }

        if (userProfile.getInterests() != null) {
            dto.setInterests(userProfile.getInterests().stream()
                    .map(interest -> {
                        UserInterestDto interestDto = new UserInterestDto();
                        interestDto.setInterestId(interest.getInterestId());
                        interestDto.setInterest(interest.getInterest());
                        return interestDto;
                    })
                    .toList());
        }

        if (userProfile.getContactPreference() != null) {
            ContactPreferenceDto contactDto = new ContactPreferenceDto();
            contactDto.setFirstName(userProfile.getContactPreference().getFirstName());
            contactDto.setLastName(userProfile.getContactPreference().getLastName());
            contactDto.setPhoneNumber(userProfile.getContactPreference().getPhoneNumber());
            contactDto.setEmailAddress(userProfile.getContactPreference().getEmailAddress());
            dto.setContactPreference(contactDto);
        }

        if (userProfile.getLocationPreference() != null) {
            dto.setLocationPreference(new LocationPreferenceDto());
        }

        if (userProfile.getSocialPreference() != null) {
            dto.setSocialPreference(new SocialPreferenceDto());
        }

        if (userProfile.getGenderPreference() != null) {
            dto.setGenderPreference(new GenderPreferenceDto());
        }

        if (userProfile.getRelationshipPreference() != null) {
            dto.setRelationshipPreference(new RelationshipPreferenceDto());
        }

        if (userProfile.getChildrenPreference() != null) {
            dto.setChildrenPreference(new ChildrenPreferenceDto());
        }

        if (userProfile.getAgePreference() != null) {
            dto.setAgePreference(new AgePreferenceDto());
        }

        if (userProfile.getReligionPreference() != null) {
            dto.setReligionPreference(new ReligionPreferenceDto());
        }

        if (userProfile.getEducationPreference() != null) {
            dto.setEducationPreference(new EducationPreferenceDto());
        }

        if (userProfile.getLanguagePreference() != null) {
            dto.setLanguagePreference(new LanguagePreferenceDto());
        }

        if (userProfile.getVicePreference() != null) {
            dto.setVicePreference(new VicePreferenceDto());
        }

        if (userProfile.getPetsPreference() != null) {
            dto.setPetsPreference(new PetsPreferenceDto());
        }

        if (userProfile.getTravelPreference() != null) {
            dto.setTravelPreference(new TravelPreferenceDto());
        }

        if (userProfile.getDietPreference() != null) {
            dto.setDietPreference(new DietPreferenceDto());
        }

        return dto;
    }

}
