package net.spotapps.tester.dto;

import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import jakarta.validation.Valid;
import net.spotapps.tester.model.UserProfile;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "userId",
        "images",
        "contactPreference",
        "location",
        "social",
        "gender",
        "relationship",
        "children",
        "age",
        "religion",
        "education",
        "language",
        "vice",
        "pets",
        "travel",
        "diet",
        "interests"
})
public class UserProfileDto {

    @JsonProperty(required = true)
    @JsonPropertyDescription("The unique identifier, generated by UserProfileService on addition")
    private Long userId;

    @JsonProperty(required = true)
    @JsonPropertyDescription("List of references to images of the user")
    private List<UserImageDto> images;

    @JsonProperty(required = true)
    @JsonPropertyDescription("The things and activities the user is interested in")
    private List<UserInterestDto> interests;

    @JsonProperty(value = "contactPreference", required = true)
    @JsonPropertyDescription("The user's contact preferences")
    @Valid
    private ContactPreferenceDto contactPreference;

    public UserProfileDto() {
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public List<UserImageDto> getImages() {
        return images;
    }

    public void setImages(List<UserImageDto> images) {
        this.images = images;
    }

    public List<UserInterestDto> getInterests() {
        return interests;
    }

    public void setInterests(List<UserInterestDto> interests) {
        this.interests = interests;
    }

    public ContactPreferenceDto getContactPreference() {
        return contactPreference;
    }

    public void setContactPreference(ContactPreferenceDto contactPreference) {
        this.contactPreference = contactPreference;
    }

    @Override
    public int hashCode() {
        return Objects.hash(contactPreference, images, interests, userId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UserProfileDto other = (UserProfileDto) obj;
        return Objects.equals(contactPreference, other.contactPreference) && Objects.equals(images, other.images)
                && Objects.equals(interests, other.interests) && Objects.equals(userId, other.userId);
    }

    @Override
    public String toString() {
        return "UserProfileDto [userId=" + userId + ", images=" + images + ", interests=" + interests
                + ", contactPreference=" + contactPreference + "]";
    }

    public static UserProfileDto convertUserProfileToDto(final UserProfile userProfile) {

        UserProfileDto dto = new UserProfileDto();
        dto.setUserId(userProfile.getUserId());

        if (userProfile.getImages() != null) {
            dto.setImages(userProfile.getImages().stream()
                    .map(image -> {
                        UserImageDto imageDto = new UserImageDto();
                        imageDto.setImageId(image.getImageId());
                        imageDto.setImage(image.getImage());
                        return imageDto;
                    })
                    .toList());
        }

        if (userProfile.getInterests() != null) {
            dto.setInterests(userProfile.getInterests().stream()
                    .map(interest -> {
                        UserInterestDto interestDto = new UserInterestDto();
                        interestDto.setInterestId(interest.getInterestId());
                        interestDto.setInterest(interest.getInterest());
                        return interestDto;
                    })
                    .toList());
        }

        if (userProfile.getContactPreference() != null) {
            ContactPreferenceDto contactDto = new ContactPreferenceDto();
            contactDto.setFirstName(userProfile.getContactPreference().getFirstName());
            contactDto.setLastName(userProfile.getContactPreference().getLastName());
            contactDto.setPhoneNumber(userProfile.getContactPreference().getPhoneNumber());
            contactDto.setEmailAddress(userProfile.getContactPreference().getEmailAddress());
            dto.setContactPreference(contactDto);
        }

        return dto;
    }

}
